# Configuration file for the Pi unit.
pi_config:
  latitude: 46.33
  longitude: -84.38
  observer_elev: 231
  cloud_threshold: 70         
  moon_threshold: 60          
  rain_threshold: 20          
  snow_threshold: 20          
  allow_rain: false           
  allow_snow: false           
  debug: true                 
  timezone: America/Detroit   
  astap_speed: slow           
  astap_search_radius: 180
  astap_fov: 0
  astap_demosaic: true        
  astap_color_correction: true
  num_sample_points: 3        
  exposure_time_us: 5000000   
  astap_speed: slow           
  astap_search_radius: 180
  astap_fov: 0
  astap_demosaic: true        
  astap_color_correction: true
  validation_margin_deg: 1.0
  astap_outputdir: Solved/
  error_log_file: error.log

temperature:
  sensor_type: 22
  gpio_pin: 4

image_calibration:
  parameter_file: calibrationParams.npz
  outputdir: Calibrated/
  output_prefix: calibrated_
  filetype: .png


streak_detection:
  min_length: 50
  border_tolerance: 10
  canny_threshold1: 50
  canny_threshold2: 150
  hough_threshold: 50
  max_line_gap: 5

pass_prediction:
  observation_period_hours: 5
  sample_interval_minutes: 1
  pass_min_elevation: 5
  min_culm_alt_threshold: 10
  tle_dir: tles
  combined_tle_file: combined.tle
  visible_passes_file: visible_satellites.tle
